Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/eoan64"

  config.vm.define :ubuntu do |server|
    server.vm.hostname = "ubuntu"
    server.vm.network "private_network", ip: "192.168.33.10"
    server.vm.network "forwarded_port", guest: 22, host: 2200, host_ip: "127.0.0.1"
  end

end
